[package]
name = "chat_client"
version = "1.0.0-dev"
edition = "2024"
authors = [ "Scott Dejong", "Nathaniel C. Moratto" ]

[dependencies]
tokio = { version = "1.8.0", features = ["rt-multi-thread", "macros", "net", "sync", "signal"]}
chat_shared = { path = "../chat_shared"  }
