[package]
name = "chat_shared"
version = "1.0.0-dev"
edition = "2024"
authors = [ "Nathaniel C. Moratto" ]

[dependencies]
tokio = { version = "1.8.0", features = ["rt-multi-thread", "macros", "net", "sync", "signal"]}
serde = { version = "1.0.228", features = ["derive"] }
ron = "0.11.0"