[package]
name = "chat_shared"
version = "1.0.0-dev"
edition = "2024"
authors = [ "Nathaniel C. Moratto", "Scott DeJong" ]

[dependencies]
tokio.workspace = true
serde.workspace = true
ron.workspace = true
uuid.workspace = true
