[package]
name = "chat_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.8.0", features = ["rt-multi-thread", "macros", "net", "sync"]}
chat_shared = {version = "0.1.0", path = "../chat_shared"}
